name: DS Dev Utils Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: [3.8.10, 3.9.13, 3.10.11, 3.11.8, 3.12.2]
        os: [windows-2019, ubuntu-20.04, macos-11]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Install self
        run: pip install -e .
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox
